services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: food_butler
      POSTGRES_PASSWORD: "jTk43LRbRqiLDexpGmmf_a1PO_dIfrim"
    volumes:
      - food_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "HLFCrPVgnN3VuXyl5vQ-dlRxdNJgaoFA"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: food_butler_test
      POSTGRES_PASSWORD: "Ggr_Le1STRXLHl4dxBBY6zFcd6tIgRxQ"
    volumes:
      - food_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "FKDTOOhDSMIpP_vcZcj2IK6r2LJnlddI"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  food_butler_data:
  food_butler_test_data:
